name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Run tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
      - name: Build if main
        uses: borales/actions-yarn@v2.3.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          cmd: build
        env:
          REACT_APP_LAMBDA_URL:  ${{ secrets.YDX_LAMBDA_HOST }}
      - name: Deploy if main
        run: aws --endpoint-url=https://storage.yandexcloud.net s3 cp --recursive ./build/ s3://${{ secrets.YDX_BUCKET_NAME }}/
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YDX_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YDX_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ru-central1
